workflows:
  android-build:
    name: Android Build
    max_build_duration: 15
    environment:
      node: 18.16.0
      npm: 9.5.1
      android_signing:
        - your_keystore_reference_if_needed
    scripts:
      - npm install
      - npm run build
      - npx cap sync
      - npx cap copy android
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk